import "./globals.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "AllMyAI",
  description: "Generated by create next app",
};

import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "react-hot-toast";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <Toaster/>
        <NextTopLoader showSpinner={false} color="#C209C1" />

        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
