import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SessionWrapper from '@/components/SessionWrapper';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <SessionWrapper>
        {children}
        </SessionWrapper>
        </body>
    </html>
  );
}
